### ISSUE TITLE
Shift doesn't work on Android Device Browser

### ISSUE THREAD

**Issue by rahulgawale** [adityanaag3/typeshift-lwc#1]
I tried to play on Android mobile but the game doesn't respond to touch and doesn't let me slid the alphabets.

**Comment by adityanaag3** [comment]
Hey @rahulgawale Thanks for flagging the issue. I fixed it in [this commit](https://github.com/adityanaag3/typeshift-lwc/commit/3b9658079c8961f6f0d1dcf2c3481c49c5debda7)
